name: Chart Generation

on:
  push:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install -U jsonpickle
      - run: python AutoProc/autoprocpy/CreateSunb.py

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: assets/JSON/flare-2.json
            commit-msg: Update resources
            github-token: ${{ secrets.GITHUB_TOKEN }}
